export default {
	FETCH_BACKGROUND_SUCCESS: 'FETCH_BACKGROUND_SUCCESS',
	FETCH_BACKGROUND_FAILURE: 'FETCH_BACKGROUND_FAILURE',

	FETCH_SETTINGS_SUCCESS: 'FETCH_SETTINGS_SUCCESS',
	FETCH_SETTINGS_FAILURE: 'FETCH_SETTINGS_FAILURE',

	CHANGE_SETTINGS_FILE_START: 'CHANGE_SETTINGS_FILE_START',
	CHANGE_SETTINGS_FILE_SUCCESS: 'CHANGE_SETTINGS_FILE_SUCCESS',
	CHANGE_SETTINGS_FILE_FAILURE: 'CHANGE_SETTINGS_FILE_FAILURE',
	CHANGE_SETTINGS_FILTER: 'CHANGE_SETTINGS_FILTER',
	CHANGE_SETTINGS_RATIO: 'CHANGE_SETTINGS_RATIO',
	CHANGE_SETTINGS_ANGLE: 'CHANGE_SETTINGS_ANGLE',
	CHANGE_SETTINGS_TEXT: 'CHANGE_SETTINGS_TEXT',
	CHANGE_SETTINGS_FONT_SIZE: 'CHANGE_SETTINGS_FONT_SIZE',
	CHANGE_SETTINGS_FONT_FAMILY: 'CHANGE_SETTINGS_FONT_FAMILY',

	START_DRAG: 'START_DRAG',
	DO_DRAG: 'DO_DRAG',
	END_DRAG: 'END_DRAG',
};